[project]
name = "python-template"
version = "0.1.0"
description = "a text to speech app for disabled people"
authors = ["Morgan Crump morganjewel01@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "werkzeug>=3.1.3",
]
